[profile.default]
solc_version = "0.8.24"
src = "contracts"
out = "contracts/out"
libs = ["contracts/lib", "contracts/lib/forge-std"]
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
  "forge-std/=contracts/lib/forge-std/src/"
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
